services:
  - type: web
    name: restaurant-website
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: restaurant-db
          property: connectionString

databases:
  - name: restaurant-db
    plan: free
